/workspace/ACCV_2024/PRCSL/src/approach/der.py:112: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  batch_exemplars.logits[i] = torch.tensor(lgt).clone().detach()
Traceback (most recent call last):
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/PIL/ImageFile.py", line 547, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/ACCV_2024/PRCSL/src/main.py", line 303, in <module>
    main()
  File "/workspace/ACCV_2024/PRCSL/src/main.py", line 251, in main
    appr.train(t, trn_loader[t], val_loader[t])
  File "/workspace/ACCV_2024/PRCSL/src/approach/incremental_learning_der.py", line 56, in train
    self.train_loop(t, trn_loader, val_loader)
  File "/workspace/ACCV_2024/PRCSL/src/approach/der.py", line 68, in train_loop
    super().train_loop(t, trn_loader, val_loader)
  File "/workspace/ACCV_2024/PRCSL/src/approach/incremental_learning_der.py", line 73, in train_loop
    self.train_epoch(t, trn_loader)
  File "/workspace/ACCV_2024/PRCSL/src/approach/der.py", line 123, in train_epoch
    plt.savefig(f'buff_img[{i}].png')
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1023, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/PIL/Image.py", line 2568, in save
    save_handler(self, fp, filename)
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 1431, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/PIL/ImageFile.py", line 551, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/opt/conda/envs/prcsl/lib/python3.8/site-packages/PIL/ImageFile.py", line 570, in _encode_tile
    errcode, data = encoder.encode(bufsize)[1:]
KeyboardInterrupt
